"""added position columns

Revision ID: 0c1501053360
Revises: fe10665015c9
Create Date: 2017-05-31 11:00:57.404837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1501053360'
down_revision = 'fe10665015c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('carry', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mid', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('offlane', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('support1', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('support2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'support2')
    op.drop_column('users', 'support1')
    op.drop_column('users', 'offlane')
    op.drop_column('users', 'mid')
    op.drop_column('users', 'carry')
    # ### end Alembic commands ###
