"""changed steamID from int to text

Revision ID: 68c793c0c1d6
Revises: 72d058cefa7b
Create Date: 2017-05-30 12:09:52.417726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c793c0c1d6'
down_revision = '72d058cefa7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('steamID', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['steamID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'steamID')
    # ### end Alembic commands ###
