"""changed steamID from int to text

Revision ID: 72d058cefa7b
Revises: 9fb2158e80da
Create Date: 2017-05-30 12:08:12.598928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d058cefa7b'
down_revision = '9fb2158e80da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_steamID_key', 'users', type_='unique')
    op.drop_column('users', 'steamID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('steamID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_steamID_key', 'users', ['steamID'])
    # ### end Alembic commands ###
