"""empty message

Revision ID: a0b077fc3849
Revises: edeeee2352d6
Create Date: 2017-06-01 11:59:49.036465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b077fc3849'
down_revision = 'edeeee2352d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teams', ['prefix'])
    op.create_unique_constraint(None, 'teams', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    # ### end Alembic commands ###
