"""included discord and MMR

Revision ID: fe10665015c9
Revises: 68c793c0c1d6
Create Date: 2017-05-30 15:03:21.529673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe10665015c9'
down_revision = '68c793c0c1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discord', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mmr', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['discord'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mmr')
    op.drop_column('users', 'discord')
    # ### end Alembic commands ###
